### ISSUE TITLE
_backward_grad() functions using =, not +=

### ISSUE THREAD

**Issue by mk-relax** [hkxIron/tensorgrad#1]
I noticed that the `_backward_grad()` functions in `SigmoidCrossEntropyWithLogitLossLayer` and `MeanSquareErrorLossLayer` use the `=` assignment operator instead of `+=`. Maybe it's correct but it seems inconsistent.

**Comment by hkxIron** [comment]
Thanks, you are right for your careful notice, I have fixed the bug. It should be "+=" , not "=", for the input tensor will receive other grad if it contribute to other loss(of course it not exists in our simple unit test)
